# Generated by Django 6.0.4 on 2026-07-31 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='is_played',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='round',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_format',
            field=models.CharField(choices=[('league', 'League'), ('knockout', 'Knockout'), ('group_knockout', 'Group + Knockout'), ('swiss', 'Swiss')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='fixture',
            constraint=models.UniqueConstraint(fields=('tournament', 'home_team', 'away_team', 'round'), name='unique_fixture_per_round'),
        ),
    ]
