# Generated by Django 6.0.4 on 2026-07-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_fixture_is_played_alter_fixture_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='is_live',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
