# Generated by Django 6.0.4 on 2026-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_team_draws_team_goals_against_team_goals_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qualify_per_group',
            field=models.IntegerField(default=2),
        ),
    ]
