# Generated by Django 6.0.4 on 2026-04-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_fixture_round_tournament_qualify_per_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
