# Generated by Django 6.0.4 on 2026-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_poll_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='knockout_phase_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='playoff_phase_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='split_phase_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_direct_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_eliminated_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_phase_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_playoff_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_format',
            field=models.CharField(choices=[('league', 'League'), ('knockout', 'Knockout'), ('group_knockout', 'Group + Knockout'), ('swiss', 'Swiss'), ('swiss_plus', 'Swiss Plus')], max_length=20),
        ),
    ]
