# Generated by Django 6.0.4 on 2026-04-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='previous_position',
            field=models.IntegerField(default=0),
        ),
    ]
