# Generated by Django 6.0.4 on 2026-04-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_team_previous_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player_name',
            field=models.CharField(default='Player', max_length=255),
        ),
    ]
