# Generated by Django 6.0.4 on 2026-08-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_knockout_phase_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='swiss_rounds_complete',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
